[package]
name = "robmon"
version = "0.1.0"
edition = "2024"

[dependencies]
nvml-wrapper = "0.11.0"
wmi = "0.17.2"
serde = "1.0.219"

[dependencies.windows]
version = "0.61.3"
features = [
  "Win32_Foundation",

  "Win32_System_Threading",

  "Win32_System_SystemInformation"

]

